apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: momo-store
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: momo-store-chart
    repoURL: >-
      https://gitlab.praktikum-services.ru/antinitrino/infra-momo-store-antinitrino.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
